import StyledComponentsRegistry from '../lib/AntdRegistry';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/AuthContext';
import { NotificationProvider } from '@/context/NotificationContext';
import Notification from '@/components/Notification';
import { cn } from '@/helper';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Alo99 Restaurant',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={cn(inter.className)}>
        <StyledComponentsRegistry>
          <AuthProvider>
            <NotificationProvider>
              <Notification />
              {children}
            </NotificationProvider>
          </AuthProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
